const Actions = {
  INIT_STATE: "LOCATION/INIT_STATE",
  SET_COLOR: "LOCATION/SET_COLOR",
  SET_SIZE: "LOCATION/SET_SIZE",
  SET_HAS_DATE: "LOCATION/SET_HAS_DATE",
  SET_HAS_TIME: "LOCATION/SET_HAS_TIME",
  SET_HAS_LOCATION: "LOCATION/SET_HAS_LOCATION",
  SET_HAS_COORDINATES: "LOCATION/SET_HAS_COORDINATES",
  SET_IS_CHANGE_TEXT: "LOCATION/SET_IS_CHANGE_TEXT",
  SET_USER_LOCATION_TEXT: "LOCATION/SET_USER_LOCATION_TEXT",
  SET_FONT_LOCATION: "LOCATION/SET_FONT_LOCATION",
};

export default Actions;
