const Actions = {
  INIT_STATE: "STARS/INIT_STATE",
  SET_HAS_GRATICULE: "STARS/SET_HAS_GRATICULE",
  SET_COLOR_GRATICULE: "STARS/SET_COLOR_GRATICULE",
  SET_HAS_DASHED_GRATICULE: "STARS/SET_HAS_DASHED_GRATICULE",
  SET_OPACITY_GRATICULE: "STARS/SET_OPACITY_GRATICULE",
  SET_OPACITY_STARS: "STARS/SET_OPACITY_STARS",
  SET_WIDTH_GRATICULE: "STARS/SET_WIDTH_GRATICULE",
  SET_HAS_MILKY_WAY: "STARS/SET_HAS_MILKY_WAY",
  SET_COLOR_STARS: "STARS/SET_COLOR_STARS",
  SET_SIZE_STARS: "STARS/SET_SIZE_STARS",
  SET_HAS_CONSTELLATIONS: "STARS/SET_HAS_CONSTELLATIONS",
  SET_COLOR_CONSTELLATIONS: "STARS/SET_COLOR_CONSTELLATIONS",
  SET_OPACITY_CONSTELLATIONS: "STARS/SET_OPACITY_CONSTELLATIONS",
  SET_WIDTH_CONSTELLATIONS: "STARS/SET_WIDTH_CONSTELLATIONS",
  SET_HAS_NAMES: "STARS/SET_HAS_NAMES",
  SET_COLOR_NAMES: "STARS/SET_COLOR_NAMES",
  SET_SIZE_NAMES: "STARS/SET_SIZE_NAMES",
  SET_LANG_NAMES: "STARS/SET_LANG_NAMES",
};

export default Actions;
