const Actions = {
  INIT_STATE: "SEPARATOR/INIT_STATE",
  SET_SHAPE_SEPARATOR_ID: "SEPARATOR/SET_SHAPE_SEPARATOR_ID",
  SET_SIZE_SEPARATOR: "SEPARATOR/SET_SIZE_SEPARATOR",
  SET_COLOR_SEPARATOR: "SEPARATOR/SET_COLOR_SEPARATOR",
  SET_HAS_SEPARATOR: "SEPARATOR/SET_HAS_SEPARATOR",
};

export default Actions;
