const Actions = {
  INIT_STATE: "DESC/INIT_STATE",
  SET_TEXT_DESC: "DESC/SET_TEXT_DESC",
  SET_FONT_DESC: "DESC/SET_FONT_DESC",
  SET_COLOR_DESC: "DESC/SET_COLOR_DESC",
  SET_SIZE_DESC: "DESC/SET_SIZE_DESC",
};

export default Actions;
