const Actions = {
  INIT_STATE: "EVENT/INIT_STATE",
  SET_DATE: "EVENT/SET_DATE",
  SET_LOCATION: "EVENT/SET_LOCATION",
  SET_LATITUDE: "EVENT/SET_LATITUDE",
  SET_LONGTITUDE: "EVENT/SET_LONGTITUDE",
  SET_VARIANTS: "EVENT/SET_VARIANTS",
  FETCH_VARIANTS: "EVENT/FETCH_VARIANTS",
  CLEAR_VARIANTS: "EVENT/CLEAR_VARIANTS",
};

export default Actions;
