const Actions = {
  INIT_STATE: "CANVAS/INIT_STATE",
  SET_HOLST_ID: "CANVAS/SET_HOLST_ID",
  SET_HOLST_COLOR: "CANVAS/SET_HOLST_COLOR",
  SET_HAS_HOLST_BORDER: "CANVAS/SET_HAS_HOLST_BORDER",
  SET_INDENT_HOLST_BORDER: "CANVAS/SET_INDENT_HOLST_BORDER",
  SET_WIDTH_HOLST_BORDER: "CANVAS/SET_WIDTH_HOLST_BORDER",
  SET_COLOR_HOLST_BORDER: "CANVAS/SET_COLOR_HOLST_BORDER",
  SET_HOLST_IMAGE_ID: "CANVAS/SET_HOLST_IMAGE_ID",
};

export default Actions;
