const Actions = {
  INIT_STATE: "MAP/INIT_STATE",
  SET_SIZE_MAP: "MAP/SET_SIZE_MAP",
  SET_MAP_COLOR: "MAP/SET_MAP_COLOR",
  SET_SHAPE_BORDER_MAP_NAME: "MAP/SET_SHAPE_BORDER_MAP_NAME",
  SET_COLOR_BORDER_MAP: "MAP/SET_COLOR_BORDER_MAP",
  SET_MARGIN_TOP_MAP: "MAP/SET_MARGIN_TOP_MAP",
  SET_HAS_BORDER_MAP: "MAP/SET_HAS_BORDER_MAP",
};

export default Actions;
