const Actions = {
  FETCH_TEMPLATES: "DATA/FETCH_TEMPLATES",
  SET_TEMPLATES: "DATA/SET_TEMPLATES",
  FETCH_CONTROLLERS: "DATA/FETCH_CONTROLLERS",
  SET_CONTROLLERS: "DATA/SET_CONTROLLERS",
  FETCH_HOLSTS: "DATA/FETCH_HOLSTS",
  SET_HOLSTS: "DATA/SET_HOLSTS",
  FETCH_COLORS: "DATA/FETCH_COLORS",
  SET_COLORS: "DATA/SET_COLORS",
  FETCH_SHAPES_BORDER_MAP: "DATA/FETCH_SHAPES_BORDER_MAP",
  SET_SHAPES_BORDER_MAP: "DATA/SET_SHAPES_BORDER_MAP",
  SET_SHAPES_SEPARATOR: "DATA/SET_SHAPES_SEPARATOR",
  FETCH_SHAPES_SEPARATOR: "DATA/FETCH_SHAPES_SEPARATOR",
  FETCH_FONTS: "DATA/FETCH_FONTS",
  SET_LOADED_FONTS: "DATA/SET_LOADED_FONTS",
  FETCH_HOLST_IMAGES: "DATA/FETCH_HOLST_IMAGES",
  SET_HOLST_IMAGES: "DATA/SET_HOLST_IMAGES",
  SET_ADDITINAL_DATA: "DATA/SET_ADDITINAL_DATA",
};

export default Actions;
