import Realm from "realm";

class ProjectSchema extends Realm.Object {
  static schema = {
    name: "Project",
    properties: {
      id: "double",
      templateComponent: "string",
      category: "string",
      title: "string",
      desc: "string",
      about: "string",
      image: "string",
      imageSize: "float[]",
      controllers: "string[]",
      latitude: "float",
      longtitude: "float",
      location: "string",
      status: "int",
      date: "date",
      textDesc: "string",
      fontDesc: "string",
      colorDesc: "string",
      sizeDesc: "int",
      holstId: "int",
      holstImageId: "int?",
      holstColor: "string",
      hasHolstBorder: "bool",
      indentHolstBorder: "int",
      widthHolstBorder: "int",
      colorHolstBorder: "string",
      fontLocation: "string",
      colorLocation: "string",
      sizeLocation: "int",
      hasDateLocation: "bool",
      hasTimeLocation: "bool",
      hasLocation: "bool",
      hasCoordinates: "bool",
      isChangeTextLocation: "bool",
      userTextLocation: "string",
      sizeMap: "int",
      mapColor: "string",
      shapeBorderMapName: "string",
      hasBorderMap: "bool",
      colorBorderMap: "string",
      marginTopMap: "int",
      shapeSeparatorId: "int",
      sizeSeparator: "int",
      hasSeparator: "bool",
      colorSeparator: "string",
      hasGraticule: "bool",
      colorGraticule: "string",
      hasDashedGraticule: "bool",
      opacityGraticule: "int",
      opacityStars: "int",
      widthGraticule: "int",
      hasMilkyWay: "bool",
      colorStars: "string",
      sizeStars: "int",
      hasConstellations: "bool",
      colorConstellations: "string",
      opacityConstellations: "int",
      widthConstellations: "int",
      hasNames: "bool",
      colorNames: "string",
      sizeNames: "int",
      langNames: "string",
    },
  };
}

export default ProjectSchema;
