export enum Routes {
  Tabs = "Tabs",
  Anothers = "Anothers",
  Modals = "Modals",
  Templates = "Templates",
  Projects = "Projects",
  Settings = "Settings",
  Template = "Template",
  ModalPickerDate = "ModalPickerDate",
  ModalPickerTime = "ModalPickerTime",
  ModalPickerLangNames = "ModalPickerLangNames",
  ModalPickerFontDesc = "ModalPickerFontDesc",
  ModalPickerFontLocation = "ModalPickerFontLocation",
  ModalPickerLatitude = "ModalPickerLatitude",
  ModalPickerLongitude = "ModalPickerLongitude",
  ModalPickerColor = "ModalPickerColor",
  ModalTextArea = "ModalTextArea",
  ModalPickerLocation = "ModalPickerLocation",
  ModalSendProblem = "ModalSendProblem",
  ModalSaveProject = "ModalSaveProject",
}
